import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  // Theme color (dark black)
  themeColor: "#000000",

  // Viewport settings
  width: "device-width",
  initialScale: 1.0,
  maximumScale: 1.0,
  userScalable: false,

  // Additional settings for better control
  shrinkToFit: false,
  viewportFit: "cover",
  minimumScale: 1.0,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
            <body className={inter.className}>
        {children}
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
